### PR TITLE
Fully working game w/o AI

### PR DESCRIPTION
**Pull request by stillonearth**
This is fully working version of game suitable for multiplayer on 1 computer. AI will be implemented in next PR.

Do you have any feedback for this?

### CODE REVIEW

**Comment by stillonearth** [comment]
https://user-images.githubusercontent.com/97428129/199034415-2aa0e8b0-7328-4e7a-ac40-e83278c46238.mp4

**Comment by quentusrex** [comment]
Did a short play through, and this is a solid start. I'm collecting some notes, and will update in the next few days. 

Is there a way to turn the dice role animation into an overlay, or a corner, instead of a full screen switch?

Next up, I want to take a swing at some of the testing parts, and start getting towards more reproducible seeded game plays. I do suspect this would involve super simple AI implementation, or at least foundations towards one.

**Comment by quentusrex** [comment]
Ok, most of the notes fall into three next areas:
1. Testing prep
a. Two tier PRNG: from a fixed starting global seed, everything needs to be able to be 're-seeded' off the original seed. For instance, world gen would take the first X bits from the root seed, then if another system needs randomness, it'd take the following X bits. This will make it FAR easier to add/change systems without effecting the reproducibility. 
b. Map invariants: Previous attempts for me ended up with a lot of trouble in map gen, and I want to make sure to invest up front in building out solid testing for map generation. I had good results from my previous attempt when expressing constraints in terms of graph requirements for edge/node constraints. Approaching this from a parameterized testing(with a fixed set of seeds that were known to be hard/bad) might help here so that changes can validate they don't change existing known map outputs, but they can resolve edge cases sanely. 
2. Events in prep for AI
a. Let's make sure to start with TURN_START, PLAYER_MOVE(can be repeated), TURN_COMPLETE, TURN_START. The turn start shares out one or more formats(depending on the AI need) for game state(incremental vs full state), and player_MOVE can send in one or more moves(these can be locally queued, but results aren't shared until 'submitted' and locked). This is an action that'll need to be able to have 'game modes' control behavior, as for AI training we'll want to be able to allow an AI to roll back and try a different move(This adds complexity around PRNG state, does the roll back also roll back the dice PRNG state). 
b. Building a test function(or even a game function that sends results in TURN_START) that would enumerate all possible player moves from a given TURN_START. This will make it trivial to create starter AI(random, simple sort based on largest advantage, etc). 
3. UI changes. 
a. kdice is a multiplayer port of the game: https://kdice.com and https://www.gamedesign.jp/games/dicewars/ is a good single player version. For visualization, I'd prefer to stay away from major screen changes(so how to layout the main UI so that game state and prompts are in their own boxes, and things don't move except on actions). 
b. We'll want to be able to use the UI interface to replay an existing game start to finish. Likely controlling the speed of replay, and being able to step forward or backwards to triage something that went strange. In replay I don't think we'll need to see things like click points, but we'll want to be able to identify source and destinations for attacks. This also means a way to clearly log actions in order, with action results(maybe just log the events in a simple way).

**Comment by quentusrex** [comment]
A bit more info on 1a, Each game should start with two separately generated RNG values. One would generate the world values, and one that is kept secret from players until the end of the game. The second one would be used to generate PRNG values for the dice rolls, and the AI moves(again two tier, dice rolls get seeded from the second value, and AI moves would be as well(this one would likely be counted as 3 tier)). This would make it FAR easier to check for cheating later, as all of the RNG based 'non-player' moves could be validated, and makes the valid move check system MUCH easier to enforce.

**Comment by quentusrex** [comment]
Expansion on 2a: 
TURN_START, PLAYER_MOVE, PLAYER_MOVE_RESULT, TURN_COMPLETE. 

This move result event is needed, so that players who make multiple moves on their turn can calibrate if they want to make another move on their turn. Likely this too may need to return valid possible moves. I'm sketching out what the event and API system is likely to look like, as there are potentially heavy events, or option API calls to fetch info not included. <- Arch decision to make later about optional heavy events, or thin events with APIs. 

The move result, should return the value for each of the dice, so the PRNG for the roll should take separate 8bit values(mod6 and add 1) for each dice in order. This provides a good visual to the user, also makes it easier to add game mode modifications(random +1 to AI dice values, etc).

**Comment by stillonearth** [comment]
As with emphasis on reproducible randomness and determinism: the dice rolls are physics based (rapier). I'm not sure if it's fully deterministic and whether is possible to substitute their source of randomness for ChaCha20Rng

**Comment by quentusrex** [comment]
Good point about the dice rolls with rapier. What would be a good alternative approach here, that would keep the invariant on reproducibility and determinism(based on game length secret)? 

On the topic, a 1a expansion is that we'll need to be able to save the Prng offsets so that future 'mid-game' tests can stay reproducible.

**Pull request merged**
